name: Front-End Storybook CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  storybook-deploy:
    runs-on: ubuntu-18.04
    env:
      name: STORYBOOK
      working-directory: ./frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm install

      - name: Deploy Storybook
        run: npx chromatic --project-token=${{ env.PAGE_TOKEN }}
